config/routes.rb
Cinema::Application.routes.draw do
  resources :movies do
    collection do
      get 'search'
    end
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @movies }
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/new
  # GET /movies/new.json
  def new
    @movie = Movie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @movie }
    end
  end

  # GET /movies/1/edit
  def edit
    @movie = Movie.find(params[:id])
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(params[:movie])

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render json: @movie, status: :created, location: @movie }
      else
        format.html { render action: "new" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /movies/1
  # PUT /movies/1.json
  def update
    @movie = Movie.find(params[:id])

    respond_to do |format|
      if @movie.update_attributes(params[:movie])
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url }
      format.json { head :ok }
    end
  end
  
  # GET /movies/search
  # This version of search uses patterns with
  # the SQL LIKE clause to support whole-word searching.

  def search
    if params[:search_text] then
      @search_text = params[:search_text]
    if params[:word_only] then
      @word_only = true
      match_term_at_start = @search_text + " %"
      match_term_at_end = "% " + @search_text
      match_term_medially = "% " + @search_text + " %"
      @movies = Movie.where("title LIKE ? OR title LIKE ? OR title LIKE ?", match_term_at_start, match_term_at_end, match_term_medially)
    else
      @word_only = false
      match_term = "%" + @search_text + "%"
      @movies = Movie.where("title LIKE ?", match_term)
    end
   end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cinema</title>
  <h3>Jimmy Kurian</h3>
  <%= stylesheet_link_tag    "style" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.date_select :year %>
  </div>
  <div class="field">
    <%= f.label :director %><br />
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Year</th>
    <th>Director</th>
    <th>Language</th>
    <th>Genre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @movies.each do |movie| %>
  <tr>
    <td><%= movie.title %></td>
    <td><%= movie.year %></td>
    <td><%= movie.director %></td>
    <td><%= movie.language %></td>
    <td><%= movie.genre %></td>
    <td><%= link_to 'Show', movie %></td>
    <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
    <td><%= link_to 'Destroy', movie, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Movie', new_movie_path %>
<%= link_to 'Search', search_movies_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/search.html.erb
<h1>Searching movies</h1>

  <%= form_tag search_movies_path, :method => 'get' do %>
  <p>
  <%= label_tag :search_tag %>
  <%= text_field_tag :search_text, @search_text %>
  </p>
  <p>
  <%= label_tag 'Check for whole word search' %>
  <%= check_box_tag :word_only, "", @word_only %>
  </p>
  <p>
  <%= submit_tag 'Search' %>
  </p>
  <% end %>
  <% if @movies then %>
    <table>
    <tr><th>Title</th><th>Year</th></tr>
    <% @movies.each do |movie| %>
    <tr><td><%= movie.title %></td><td><%= movie.year %></td></tr>
    <% end %>
    </table>
  <% end %>
<br />

<%= link_to 'New Movie', new_movie_path %>
<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @movie.title %>
</p>

<p>
  <b>Year:</b>
  <%= @movie.year %>
</p>

<p>
  <b>Director:</b>
  <%= @movie.director %>
</p>

<p>
  <b>Language:</b>
  <%= @movie.language %>
</p>

<p>
  <b>Genre:</b>
  <%= @movie.genre %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>